### ISSUE TITLE
authservice hanging using an Azure AD application

### ISSUE THREAD

**Issue by dippynark** [istio-ecosystem/authservice#114]
I have deployed authservice as its own Deployment in its own Namespace and am trying to configure authentication to a service using an Azure AD application. The setup is working except that the call to Azure (I believe when retrieving the ID token) hangs for about 2 minutes when logging in (2m 8s with a stopwatch). Potentially this is related to [this](https://github.com/istio-ecosystem/authservice/issues/97) issue but I wasn't sure.

Potentially this is due to configuration on the Azure AD side, however I am using the same application to authenticate to other separate services using OIDC (e.g. Vault) and everything works as expected, so I believe there is something that can be done on the authservice side to fix this.

I have attached logs for authservice below as well as its sidecar and the sidecar of the service I want to authenticate to (Kiali) as described [here](https://github.com/istio-ecosystem/authservice/issues/93).

I am using the following resources to enforce authn/z by Istio:

```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: kiali
  namespace: kiali
spec:
  selector:
    matchLabels:
      app: kiali
  jwtRules:
  - issuer: https://login.microsoftonline.com/<APPLICATION_ID>/v2.0
    jwksUri: https://login.microsoftonline.com/<APPLICATION_ID>/discovery/v2.0/keys
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: kiali
  namespace: kiali
spec:
  selector:
    matchLabels:
      app: kiali
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
```

As well as the following EnvoyFilters to allow authservice to intervene:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authservice
  namespace: kiali
spec:
  workloadSelector:
    labels:
      app: kiali
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.jwt_authn"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.ext_authz
       config:
         stat_prefix: ext_authz
         grpc_service:
           envoy_grpc:
             cluster_name: patched.authservice.authservice.svc.cluster.local
           timeout: 300s # Increased this to 5 mins due to the issue described
---
# https://github.com/istio/istio/issues/21841
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authservice-cluster-patch
  namespace: kiali
spec:
  workloadSelector:
    labels:
      app: kiali
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        service: authservice.authservice.svc.cluster.local
    patch:
      operation: MERGE
      value:
        name: patched.authservice.authservice.svc.cluster.local
```

My authservice configuration looks like:

```json
{
  "listen_address": "0.0.0.0",
  "listen_port": "10003",
  "log_level": "trace",
  "threads": 8,
  "chains": [
    {
      "name": "idp_filter_chain",
      "filters": [
      {
        "oidc":
          {
            "client_id": "[REDACTED]",
            "client_secret": "[REDACTED]",
            "authorization_uri": "https://login.microsoftonline.com/<APPLICATION_ID>/oauth2/v2.0/authorize",
            "token_uri": "https://login.microsoftonline.com/<APPLICATION_ID>/oauth2/v2.0/token",
            "jwks": "<REDACTED>",
            "callback_uri": "https://kiali.[REDACTED]/oidc/callback",
            "scopes": [],
            "id_token": {
              "preamble": "Bearer",
              "header": "Authorization"
            },
            "logout": {
              "path": "/authservice_logout",
              "redirect_uri": "https://kiali.[REDACTED]"
            }
          }
        }
      ]
    }
  ]
}
```

I am using the latest version of authservice (0.3.1) and of Istio (1.6.5).

[kiali-proxy.log](https://github.com/istio-ecosystem/authservice/files/4932186/kiali-proxy.log)
[authservice.log](https://github.com/istio-ecosystem/authservice/files/4932182/authservice.log)
[authservice-proxy.log](https://github.com/istio-ecosystem/authservice/files/4932181/authservice-proxy.log)

**Comment by markszabo** [comment]
hi @dippynark did you figure out a solution to this? 

I'm facing the same issue, and I really can't get my head around it. Setting the token URL to a site that logs the request, and then manually sending the request to login.microsoftonline.com works as expected 🤔

**Comment by markszabo** [comment]
I managed to setup a proxy that terminates TLS and simply forwards the request to login.microsoftonline.com and that worked. My guess is that authservice doesn't like the certificate of login.microsoftonline.com, but this is just guessing (based on the fact that everything else is the same with the proxy setup).

Here is how I set up the proxy:

1.  Download and install [burp suite](https://portswigger.net/burp/communitydownload)
2. Configure the proxy to listen on all interfaces, and enable `Invisible` mode. Export the CA certificate in DER format
    ![image](https://user-images.githubusercontent.com/12611720/136486343-4d36f3e9-5aaa-4edd-b48c-f292ff1f96a0.png)
3. Convert the certificate to pem: `openssl x509 -in cacert.der -inform DER -out cacert2.pem -outform PEM`
4. Replace the new lines with `\n` in the certificate to get something like this: `-----BEGIN CERTIFICATE-----\nMIIH0DCCBrigAwIBAgIQCDHtasOWiQVFocXX2//+wjANBgkqhkiG9...w0BAQsFADBRb/5\n6tqE+0BOK1TBYR4scXNZO7CIgUyEISius6U2WYm98KIjt3uo\n-----END CERTIFICATE-----`
5. Setup port forwarding on your home router to forward port 443 to port 8080 on the machine burp is running on
6. Get your public IPv4 address
7. Set the [`"trusted_certificate_authority"`](https://github.com/istio-ecosystem/authservice/blob/master/docs/README.md#:~:text=uint32-,trusted_certificate_authority,-When%20specified%2C%20the) config option to the certificate from the previous step
8. Leave the `"token_uri": "https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/token"`
8. For the `authservice` `Deployment` configure a [`hostAlias`](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#adding-additional-entries-with-hostaliases):
   ```yaml
   template:
    metadata:
      labels:
        app: authservice
    spec:
      hostAliases:
      - ip: "1.2.3.4" # set it to your home IP
        hostnames:
        - "login.microsoftonline.com"
      volumes:
   ```
9. Make sure intercept is turned off in burp
    ![image](https://user-images.githubusercontent.com/12611720/136486766-7c58d5c3-c9f3-4e85-a9d7-cfe131262a0c.png)

Now it should work, and you should also see the requests and responses showing up in burp.
