### ISSUE TITLE
Update to Istio 1.6+

### ISSUE THREAD

**Issue by margocrawf** [istio-ecosystem/authservice#116]
Ensure that our project is compatible with Istio 1.6 (or 1.7 once it's out)

**Comment by margocrawf** [comment]
#106 seems to point to a problem with the way headers are preserved when they pass through the Istio RBAC components.

**Comment by ipuustin** [comment]
The examples also talk about `Policy` CRDs, even though they are removed from Istio 1.6 and 1.7. `RequestAuthentication` + `AuthorizationPolicy` should be used instead AFAIK.

**Comment by cflewis** [comment]
I just hit the examples problem. I only found out once I hit the Policy CRD :facepalm: 

It would be very good if this was fixed, it's very unclear to me how to transition this CRD to the new ones.

**Comment by cflewis** [comment]
@cfryanr for visibility, as there's no way to onboard people to use `authservice` at this point.

**Comment by jeff-mccoy** [comment]
We're using with Istio 1.7 with Authservice running in it's own namespace and only using ext_authz from Envoy.  We add the label `protect: keycloak` for any workloads we need to protect and do not use Istio's additional Authz/Authn CRDs. 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz-filter-cluster
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      protect: keycloak
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz"
            stat_prefix: ext_authz
            grpc_service:
              timeout: 30s
              google_grpc:
                stat_prefix: ext_authz
                target_uri: authservice.authservice.svc.cluster.local:10003
```
