### ISSUE TITLE
Authservice should implicitly deny requests that don't match config prefixes

### ISSUE THREAD

**Issue by atoy3731** [istio-ecosystem/authservice#140]
## Issue

Currently, a request to a workload that is authservice-enabled that does *not* match one of the prefixes in the authservice config will allow the request.

## Recreation

1. Spin up authservice with ext_authz envoyfilter
2. Deploy Istio gateway/virtualservice for application that does *not* match chain in authservice config
3. Deploy workload matching envoyfilter selector using above virtualservice
4. Access the application using the VS domain/routes, traffic will be allowed even though it isn't specified in config.

## Expected behavior

If a workload is authservice-enabled and it doesn't match a filter in the chain, it should be denied.

**Comment by incfly** [comment]
I am a bit confused on the problem statement. Could you elaborate a bit?  Some sample configuration would help.

> If a workload is authservice-enabled

This means envoyfilter created on the workload correct?

> it doesn't match a filter in the chain

What does this mean? The virtual service/gateway contains the paths `[a,b]`, but the client browser is trying to access `/c` and should be denied?

**Comment by atoy3731** [comment]
Using this example config:
```
{
  "listen_address": "0.0.0.0",
  "listen_port": "10003",
  "log_level": "trace",
  "default_oidc_config": {
    "authorization_uri": "REDACTED",
    "token_uri": "REDACTED",
    "jwks": "REDACTED",
    "client_id": "REDACTED",
    "client_secret": "REDACTED",
    "cookie_name_prefix": "REDACTED",
    "id_token": {
      "preamble": "Bearer",
      "header": "Authorization"
    },
    "access_token": {
      "header": "JWT"
    },
    "trusted_certificate_authority": "REDACTED",
    "logout": {
      "path": "/oauth/logout",
      "redirect_uri": "REDACTED"
    },
    "scopes": []
  },
  "threads": 8,
  "chains": [
    {
      "name": "test",
      "match": {
        "header": ":authority",
        "prefix": "test.example.com"
      },
      "filters": [
        {
          "oidc_override": {
            "redis_session_store_config": {
              "server_uri": "tcp://REDACTED:6379"
            },
            "callback_uri": "https://test.example.com/oauth/callback",
            "cookie_name_prefix": "test",
            "logout": {
              "redirect_uri": "https://REDACTED/logout"
            },
            "scopes": []
          }
        }
      ]
    }
  ]
}
```
Right now if a request comes into a sidecar for `no-match.example.com`, matches the envoyfilter and proxies to the authservice, because it does *not* match a prefix (the only one in this config being `test.example.com`), it will fail open and be allowed through.

It'd be ideal if a request is proxied to the authservice, and it does *not* match any chains, the request would be denied.

**Comment by incfly** [comment]
I see. It sounds like this use case want to ensure the application behind sidecar/gateway is always protected under OIDC. I think this is possible in updated config example. I can verify it a bit.

BTW, are you enabling authservice on application sidecar or the ingress gateway?

**Comment by incfly** [comment]
I tried with 0.5.1 image, which should include #183. However it does not have intended behavior: the request with unmatched `:authority` header still able to get through. when unmatched host is found, we returns earlier here.

However,  I don't think we should go after fixing that. Instead I still think we should achieve this via Istio RequestAuthentication and AuthorizationPolicy.

People using this repo would always use Istio. Istio authn & authz policy has already supports such use case: we should configure a request authentication to validate the id token, and then in the authorization policy we can specify `to.hosts`, to require a `requestPrincipals`. For the unmatched ones, all requests will get 403 rbac denied.

Additionally istio authz allows much richer flexibility in terms of when to allow or deny requests (conditions, app label selector). Authservice in this case can be just viewed as a token acquisition component.

I have tested and here is some sample configuration for the bookinfo product page. I am using accounts.google.com as IdP. And access it via localhost:8443.

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "productpage-jwt"
spec:
  selector:
    matchLabels:
      app: productpage
  jwtRules:
  - issuer: "https://accounts.google.com"
    jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "productpage-only-allow-authenticated-access"
spec:
  selector:
    matchLabels:
      app: productpage
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts: ["localhost:8443"]
    from:
    - source:
        requestPrincipals: ["*"]
```
