### ISSUE TITLE
Use new authN api in our bookinfo example

### ISSUE THREAD

**Issue by andrewedstrom** [istio-ecosystem/authservice#85]
Per @rshriram's suggestion in the [istio slack](https://istio.slack.com/archives/C3TEGNZ7W/p1583794692142700), we should update https://github.com/istio-ecosystem/authservice/blob/master/bookinfo-example/config/bookinfo-authn-policy-template-adding-reviews.yaml to use the [new authN api](https://istio.io/docs/tasks/security/authentication/authn-policy/)

I believe it's called [RequestAuthentication](https://istio.io/docs/reference/config/security/request_authentication/). Should be a pretty small fix.

**Comment by zimmertr** [comment]
I believe they will look something like this. Can anyone confirm? I am having trouble determining if I have misconfigured the RequestAuthentication and AuthorizationPolicy.


```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: bookinfo-productpage
  namespace: bookinfo
spec:
  selector:
    matchLabels:
      app: productpage
  jwtRules:
  - issuer: https://kubernetes.docker.internal/auth/realms/example
    jwksUri: https://kubernetes.docker.internal/auth/realms/example/protocol/openid-connect/certs
  principalBinding: USE_ORIGIN
```

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: bookinfo-productpage
spec:
  selector:
    matchLabels:
      app: productpage
  # rules:
  # - from:
  #   - source:
  #       requestPrincipals: ["*"]

```
